version: 0.1

phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
  build:
    commands:
      - docker build --tag 589954089043.dkr.ecr.ap-southeast-2.amazonaws.com/devops/sample_repo:latest .
  post_build:
    commands:
      - docker push 589954089043.dkr.ecr.ap-southeast-2.amazonaws.com/devops/sample_repo:latest
